[General]
hotkey=Ctrl+Space
notifiedUnsupportedHotkey=true
showTray=true
telemetry=false
terminal=Alacritty

[applications_xdg]
enabled=true
use_exec=false
use_generic_name=true
use_keywords=true
use_non_localized_name=true

[calculator_qalculate]
enabled=false

[chromium]
bookmarks_path=/home/zhurai/.config/chromium/Default/Bookmarks
enabled=false

[datetime]
enabled=true

[docs]
enabled=false

[files]
enabled=true
paths=@Invalid()

[hash]
enabled=true

[python]
enabled=true
watchSources=false

[qmlboxmodel]
alwaysOnTop=true
windowPosition=@Point(0 0)

[ssh]
enabled=false

[system]
enabled=false

[terminal]
enabled=true

[urlhandler]
enabled=true

[websearch]
enabled=false
