[General]
notifiedUnsupportedHotkey=true
showTray=true
telemetry=false
terminal=Alacritty

[applications_xdg]
enabled=true
use_exec=false
use_generic_name=false
use_keywords=false

[calculator_qalculate]
enabled=true

[datetime]
enabled=true

[docs]
enabled=false

[files]
enabled=true

[hash]
enabled=true

[python]
enabled=true
watchSources=false

[qmlboxmodel]
alwaysOnTop=true

[terminal]
enabled=true

[urlhandler]
enabled=true

[websearch]
enabled=true
