# Kill focused window
bind = $mod, Q, killactive,

# Exit hyprland (logs you out of your Wayland session)
#bind = $mod Shift, E, exit,

# Fullscreen active window
bind = $mod, F, fullscreen

# Float/Unfloat active window
#bind = $mainMod, V, togglefloating,

#bind = $mainMod, P, pseudo, # dwindle
#bind = $mainMod, J, togglesplit, # dwindle
#bind = $mainMod, E, exec, dolphin
