bind = $mod, z, movefocus, l
bind = $mod, z, movefocus, u

bind = $mod, x, movefocus, r
bind = $mod, x, movefocus, d

bind = $mod, Page_Up, movefocus, l
bind = $mod, Page_Up, movefocus, u 

bind = $mod, Page_Down, movefocus, r
bind = $mod, Page_Down, movefocus, d

bind = Alt, Tab, movefocus, r
bind = Alt, Tab, movefocus, d
