bind = $mod, Z, movefocus, l
bind = $mod, Z, movefocus, u

bind = $mod, X, movefocus, r
bind = $mod, X, movefocus, d

bind = $mod, Page_Up, movefocus, l
bind = $mod, Page_Up, movefocus, u 

bind = $mod, Page_Down, movefocus, r
bind = $mod, Page_Down, movefocus, d

bind = Alt, Tab, movefocus, r
bind = Alt, Tab, movefocus, d
