bindn = ,Tab, exec, /home/zhurai/.bin/arknights/arknights.farming.startnext.sh

bindn = ,2, exec, /home/zhurai/.bin/arknights/arknights.raiding.pause.sh
bindn = ,S, exec, /home/zhurai/.bin/arknights/arknights.raiding.pause.sh
bindn = ,Space, exec, /home/zhurai/.bin/arknights/arknights.raiding.pause.sh
bindn = ,W, exec, /home/zhurai/.bin/arknights/arknights.raiding.pause.sh
bindn = ,X, exec, /home/zhurai/.bin/arknights/arknights.raiding.pause.sh

bindn = ,Grave, exec, /home/zhurai/.bin/arknights/arknights.raiding.pause2.sh

bindn = ,4, exec, /home/zhurai/.bin/arknights/arknights.raiding.retreat.sh
bindn = ,F, exec, /home/zhurai/.bin/arknights/arknights.raiding.retreat.sh
bindn = ,R, exec, /home/zhurai/.bin/arknights/arknights.raiding.retreat.sh
bindn = ,V, exec, /home/zhurai/.bin/arknights/arknights.raiding.retreat.sh

bindn = ,3, exec, /home/zhurai/.bin/arknights/arknights.raiding.skill.sh
bindn = ,C, exec, /home/zhurai/.bin/arknights/arknights.raiding.skill.sh
bindn = ,D, exec, /home/zhurai/.bin/arknights/arknights.raiding.skill.sh
bindn = ,E, exec, /home/zhurai/.bin/arknights/arknights.raiding.skill.sh

bindn = ,1, exec, /home/zhurai/.bin/arknights/arknights.raiding.speed.sh
bindn = ,A, exec, /home/zhurai/.bin/arknights/arknights.raiding.speed.sh
bindn = ,Q, exec, /home/zhurai/.bin/arknights/arknights.raiding.speed.sh
bindn = ,Z, exec, /home/zhurai/.bin/arknights/arknights.raiding.speed.sh
