# switch to a specific workspace
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Change to previous/next workspace with left/right
bind = $mod, left, workspace, e-1
bind = $mod, right, workspace, e+1

# Change first/last workspace with up/down
bind = $mod, down, workspace, 1
#bind = $mod, up, workspace, 1
#bind = $mod, up, workspace, -1
#bindsym $mod+Down workspace 1 
#bindsym $mod+Up workspace 1 ; workspace prev

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
