# Application Launcher
windowrulev2 = float, class:(Rofi)

# Steam workarounds
windowrulev2 = stayfocused, title:^()$, class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$, class:^(steam)$

# Genymotion workarounds
windowrulev2 = workspace special:popups silent, title:^Genymotion$, class:^Genymotion Player$
