# Terminals
windowrulev2 = workspace $ws-terminal silent,class:(Alacritty)
#windowrulev2 = workspace $ws-terminal silent,class:(kitty)

# VS Code
windowrulev2 = workspace $ws-code silent,class:(code-url-handler)

# Sublime Editor
windowrulev2 = workspace $ws-code silent,class:(sublime_text)


