# Mahjong Soul
windowrulev2 = workspace 03 silent,class:^(chromium),title:^(MahjongSoul - Chromium)$

# Steam games
windowrulev2 = workspace 03 silent,class:^(steam_app_)(.*)$

# Minecraft
windowrulev2 = workspace 03 silent,class:(Minecraft)
windowrulev2 = fullscreen,class:(Minecraft)
