# Arknights (Waydroid)
windowrulev2 = workspace $ws-games-focus silent,class:(.*waydroid.*)
#windowrulev2 = fullscreen,class:(.*waydroid.*)

# Waydroid
windowrulev2 = workspace $ws-games-focus silent,class:(.*Waydroid.*)
#windowrulev2 = fullscreen,class:(.*Waydroid.*)
