# Arknights (Waydroid)
windowrulev2 = workspace 04 silent,class:(.*waydroid.*)
#windowrulev2 = fullscreen,class:(.*waydroid.*)

# Waydroid
windowrulev2 = workspace 04 silent,class:(.*Waydroid.*)
#windowrulev2 = fullscreen,class:(.*Waydroid.*)
