# Genymotion
windowrulev2 = workspace $ws-games,class:(Genymotion Player)

# Waydroid
windowrulev2 = workspace $ws-games,class:(Waydroid)

# Lutris/Wine - Counter Side
windowrulev2 = workspace $ws-games,class:(counterside.exe)
