# Genymotion
windowrulev2 = workspace $ws-games silent,title:^(?!Genymotion$),class:(Genymotion Player)
windowrulev2 = fullscreen,title:^(?!Genymotion$),class:(Genymotion Player)

# Scrcpy
windowrulev2 = workspace $ws-games silent,class:(scrcpy)
#windowrulev2 = fullscreen,class:(scrcpy)

# Chromium - Granblue
windowrulev2 = workspace $ws-games silent,class:(vivaldi-stable)

# Steam - Counterside
windowrulev2 = workspace $ws-games silent,class:(steam_app_1976440)
windowrulev2 = tile,class:(steam_app_1976440)

# Steam - Limbus
windowrulev2 = workspace $ws-games silent,class:(steam_app_1973530)
windowrulev2 = tile,class:(steam_app_1973530)
