# MTGO
windowrulev2 = workspace 6 silent,class:(mtgo.exe)
windowrulev2 = float,class:(mtgo.exe)
windowrulev2 = size 1920 1080,class:(mtgo.exe),title:(Magic: The Gathering Online)
windowrulev2 = move 0 0,class:(mtgo.exe),title(Magic: The Gathering Online)
windowrule = opacity 1.0 override 1.0 override 1.0 override,^(mtgo.exe)$
