# Pavucontrol
windowrulev2 = workspace $ws-general silent,class:(pavucontrol)
windowrulev2 = workspace 10 silent,class:(WebCord)
windowrulev2 = workspace 10 silent,class:(vesktop)

# Steam
windowrulev2 = workspace 8 silent,class:(^steam$)

# Battle.NET

# Lutris

# Prism Launcher
