[[tasks]]
type = "Infrast"

[tasks.params]
mode = 10000
facility = [
  "Control",
  "Trade",
  "Mfg",
  "Power",
  "Office",
  "Reception",
  "Training",
  "Dorm",
]
filename = "default.json"
replenish = true
continue_training = true

# 01:00-13:00 Infra Rotation
[[tasks.variants]]
condition = { type = "Time", start = "01:00:00", end = "12:59:59" }
params = { plan_index = { default = 0, description = "index of plan" } }

# 13:00-19:00 Infra Rotation
[[tasks.variants]]
condition = { type = "Time", start = "13:00:00", end = "18:59:59" }
params = { plan_index = { default = 1, description = "index of plan" } }

# 19:00-1:00 Infra Rotation
[[tasks.variants]]
condition = { type = "Time", start = "19:00:00", end = "00:59:59" }
params = { plan_index = { default = 2, description = "index of plan" } }

