[[tasks]]
type = "StartUp"
params = { client_type = "YostarEN", start_game_enabled = true }

[[tasks]]
type = "Mall"
[tasks.params]
shopping = true
credit_fight = false
buy_first = ["Skill Summary - 2"]
blacklist = ["Carbon Stick", "Carbon Brick", "Pure Gold", "Furniture Part", "LMD", "Expedited Plan"]

[[tasks]]
type = "Infrast"

[tasks.params]
mode = 10000
facility = [
  "Control",
  "Trade",
  "Mfg",
  "Power",
  "Office",
  "Reception",
  "Training",
  "Dorm",
]
filename = "default.json"
replenish = true
continue_training = true

# 01:00-13:00 Infra Rotation
[[tasks.variants]]
condition = { type = "Time", start = "01:00:00", end = "12:59:59" }
params = { plan_index = { default = 0, description = "index of plan" } }

# 13:00-19:00 Infra Rotation
[[tasks.variants]]
condition = { type = "Time", start = "13:00:00", end = "18:59:59" }
params = { plan_index = { default = 1, description = "index of plan" } }

# 19:00-1:00 Infra Rotation
[[tasks.variants]]
condition = { type = "Time", start = "19:00:00", end = "00:59:59" }
params = { plan_index = { default = 2, description = "index of plan" } }

[[tasks]]
type = "Fight"

[tasks.params]
expiring_medicine = 1000

[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Mon"] }
params = { stage = "AP-5" }

[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Tue", "Thu", "Sat", "Sun"] }
params = { stage = "CE-6" }

[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Wed"] }
# condition = { type = "Weekday", weekdays = ["Wed", "Fri"] }
params = { stage = "CA-5" }

[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Fri"] }
params = { stage = "LS-6" }

[[tasks]]
type = "Award"

[tasks.params]
award = true
mail = true
orundum = true
specialaccess = true

