local awful = require("awful")

awful.util.spawn("/usr/bin/slack")
awful.util.spawn("/usr/bin/discord")
awful.util.spawn("/usr/bin/remmina")
awful.util.spawn("/usr/bin/autokey-gtk")
awful.util.spawn("/usr/bin/steam")
awful.util.spawn("/usr/bin/bitwarden-desktop")
awful.util.spawn("/usr/bin/blueman-applet")
awful.util.spawn("/usr/bin/pavucontrol")
